const contracts = [
  { id: 'home.fetchHome', modulePath: 'services/home/home.js', fn: 'fetchHome', args: [] },
  { id: 'activity.fetchActivity', modulePath: 'services/activity/fetchActivity.js', fn: 'fetchActivity', args: [0] },
  { id: 'activity.fetchActivityList', modulePath: 'services/activity/fetchActivityList.js', fn: 'fetchActivityList', args: [1, 2] },
  { id: 'address.fetchDeliveryAddress', modulePath: 'services/address/fetchAddress.js', fn: 'fetchDeliveryAddress', args: [0] },
  { id: 'address.fetchDeliveryAddressList', modulePath: 'services/address/fetchAddress.js', fn: 'fetchDeliveryAddressList', args: [2] },
  { id: 'cart.fetchCartGroupData', modulePath: 'services/cart/cart.js', fn: 'fetchCartGroupData', args: [] },
  {
    id: 'comments.fetchComments',
    modulePath: 'services/comments/fetchComments.js',
    fn: 'fetchComments',
    args: [{ queryParameter: { hasImage: false } }],
  },
  { id: 'comments.fetchCommentsCount', modulePath: 'services/comments/fetchCommentsCount.js', fn: 'fetchCommentsCount', args: [0] },
  { id: 'coupon.fetchCouponList', modulePath: 'services/coupon/index.js', fn: 'fetchCouponList', args: ['default'] },
  { id: 'coupon.fetchCouponDetail', modulePath: 'services/coupon/index.js', fn: 'fetchCouponDetail', args: [0, 'default'] },
  {
    id: 'good.createGoods',
    modulePath: 'services/good/createGoods.js',
    fn: 'createGoods',
    args: [
      {
        title: 'Sample Goods',
        price: 19900,
        originPrice: 19900,
        thumb: 'https://example.com/sample.png',
        storeId: '1000',
        spuId: 'sample-1',
        skuId: 'sample-1',
      },
    ],
    ignoreKeys: ['createdAt'],
  },
  { id: 'good.getCategoryList', modulePath: 'services/good/fetchCategoryList.js', fn: 'getCategoryList', args: [] },
  { id: 'good.fetchGood', modulePath: 'services/good/fetchGood.js', fn: 'fetchGood', args: [0] },
  { id: 'good.fetchGoodsList', modulePath: 'services/good/fetchGoods.js', fn: 'fetchGoodsList', args: [1, 1] },
  {
    id: 'good.fetchGoodsListSearch',
    modulePath: 'services/good/fetchGoodsList.js',
    fn: 'fetchGoodsList',
    args: [{ pageNum: 1, pageSize: 10, keyword: '' }],
  },
  {
    id: 'good.getGoodsDetailsCommentsCount',
    modulePath: 'services/good/fetchGoodsDetailsComments.js',
    fn: 'getGoodsDetailsCommentsCount',
    args: [0],
  },
  {
    id: 'good.getGoodsDetailsCommentList',
    modulePath: 'services/good/fetchGoodsDetailsComments.js',
    fn: 'getGoodsDetailsCommentList',
    args: [0],
  },
  { id: 'good.getSearchHistory', modulePath: 'services/good/fetchSearchHistory.js', fn: 'getSearchHistory', args: [] },
  { id: 'good.getSearchPopular', modulePath: 'services/good/fetchSearchHistory.js', fn: 'getSearchPopular', args: [] },
  {
    id: 'good.getSearchResult',
    modulePath: 'services/good/fetchSearchResult.js',
    fn: 'getSearchResult',
    args: [{ pageNum: 1, pageSize: 10, keyword: '航天' }],
  },
  {
    id: 'good.getCommentDetail',
    modulePath: 'services/good/comments/fetchCommentDetail.js',
    fn: 'getCommentDetail',
    args: [{ spuId: '0', skuId: '135676631', orderNo: '354021731671873099' }],
  },
  {
    id: 'order.fetchRightsPreview',
    modulePath: 'services/order/applyService.js',
    fn: 'fetchRightsPreview',
    args: [{ orderNo: '132222623132329291', skuId: '135676631' }],
  },
  {
    id: 'order.dispatchConfirmReceived',
    modulePath: 'services/order/applyService.js',
    fn: 'dispatchConfirmReceived',
    args: [],
  },
  {
    id: 'order.fetchApplyReasonList',
    modulePath: 'services/order/applyService.js',
    fn: 'fetchApplyReasonList',
    args: [{ rightsReasonType: 'REFUND_MONEY' }],
  },
  {
    id: 'order.dispatchApplyService',
    modulePath: 'services/order/applyService.js',
    fn: 'dispatchApplyService',
    args: [{ orderNo: '132222623132329291', reasonId: '1' }],
  },
  {
    id: 'order.fetchSettleDetail',
    modulePath: 'services/order/orderConfirm.js',
    fn: 'fetchSettleDetail',
    args: [
      {
        goodsRequestList: [
          {
            storeId: '1000',
            spuId: '0',
            skuId: '135676631',
            title: '航天神舟牌鱼蛋白粉固体饮料',
            primaryImage: 'https://youke3.picui.cn/s1/2026/01/06/695c78fdae97a.png',
            quantity: 1,
            price: 95800,
            originPrice: 100000,
            specInfo: [],
          },
        ],
        couponList: [],
        userAddressReq: null,
      },
    ],
  },
  {
    id: 'order.dispatchCommitPay',
    modulePath: 'services/order/orderConfirm.js',
    fn: 'dispatchCommitPay',
    args: [{}],
    ignoreKeys: ['tradeNo', 'transactionId'],
  },
  {
    id: 'order.dispatchSupplementInvoice',
    modulePath: 'services/order/orderConfirm.js',
    fn: 'dispatchSupplementInvoice',
    args: [],
  },
  {
    id: 'order.fetchOrderDetail',
    modulePath: 'services/order/orderDetail.js',
    fn: 'fetchOrderDetail',
    args: [{ parameter: '354021731671873099' }],
  },
  {
    id: 'order.fetchBusinessTime',
    modulePath: 'services/order/orderDetail.js',
    fn: 'fetchBusinessTime',
    args: [{}],
  },
  {
    id: 'order.fetchOrders',
    modulePath: 'services/order/orderList.js',
    fn: 'fetchOrders',
    args: [{ parameter: { pageNum: 1, pageSize: 2, orderStatus: -1 } }],
  },
  {
    id: 'order.fetchOrdersCount',
    modulePath: 'services/order/orderList.js',
    fn: 'fetchOrdersCount',
    args: [{ parameter: { orderStatus: -1 } }],
  },
  {
    id: 'order.orderSubmitCommentGoods',
    modulePath: 'services/order/orderSubmitComment.js',
    fn: 'getGoods',
    args: [{}],
  },
  { id: 'promotion.fetchPromotion', modulePath: 'services/promotion/detail.js', fn: 'fetchPromotion', args: [0] },
  { id: 'usercenter.fetchUserCenter', modulePath: 'services/usercenter/fetchUsercenter.js', fn: 'fetchUserCenter', args: [] },
  { id: 'usercenter.fetchPerson', modulePath: 'services/usercenter/fetchPerson.js', fn: 'fetchPerson', args: [] },
];

module.exports = { contracts };
